// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {uiapi} from '../models';
import {datasyncui} from '../models';
import {eventstatus} from '../models';
import {status} from '../models';
import {appconfig} from '../models';
import {rulecheck} from '../models';

export function ApplyManagedInstall(arg1:uiapi.ManagedInstallRequest):Promise<uiapi.ManagedInstallResponse>;

export function ApplyQueueEventQuarantine(arg1:datasyncui.QueueEventApplyRequest):Promise<datasyncui.QueueAuditReceiptDTO>;

export function ExportDiagnosticPackage():Promise<uiapi.DiagnosticPackageResponse>;

export function GetAgentProcessStatus():Promise<uiapi.AgentProcessStatus>;

export function GetAuthState():Promise<uiapi.AuthState>;

export function GetAutoStart():Promise<uiapi.AutoStartStatus>;

export function GetCapabilities():Promise<uiapi.CapabilitiesResponse>;

export function GetConfig():Promise<uiapi.ConfigDTO>;

export function GetDeadLetters(arg1:uiapi.DeadLetterRequest):Promise<uiapi.DeadLetterResponse>;

export function GetEventStatus(arg1:eventstatus.Request):Promise<eventstatus.Response>;

export function GetFailedEvents(arg1:uiapi.FailedEventsRequest):Promise<uiapi.FailedEventsResponse>;

export function GetLogs(arg1:uiapi.LogQuery):Promise<uiapi.LogsResponse>;

export function GetMCPServerStatus():Promise<uiapi.MCPServerStatus>;

export function GetManagedInstallPlan(arg1:uiapi.ManagedInstallRequest):Promise<uiapi.ManagedInstallResponse>;

export function GetNodeOptions():Promise<uiapi.NodeOptionsResponse>;

export function GetOverview():Promise<status.Overview>;

export function GetQueueEventAudit(arg1:datasyncui.QueueEventAuditRequest):Promise<datasyncui.QueueAuditReceiptDTO>;

export function GetQueueStatus():Promise<uiapi.QueueStatusResponse>;

export function GetSyncRules():Promise<uiapi.SyncRulesDTO>;

export function LoadConfig(arg1:string):Promise<appconfig.Config>;

export function LockAdmin():Promise<uiapi.OperationResult>;

export function PlanQueueEventQuarantine(arg1:datasyncui.QueueEventPlanRequest):Promise<datasyncui.QueueAuditReceiptDTO>;

export function PreflightSyncRule(arg1:datasyncui.RulePreflightRequest):Promise<rulecheck.Result>;

export function RequestExit(arg1:uiapi.VerifyExitPasswordRequest):Promise<uiapi.OperationResult>;

export function RestartAgent():Promise<uiapi.OperationResult>;

export function RetryFailedEvent(arg1:uiapi.RetryFailedEventRequest):Promise<uiapi.OperationResult>;

export function RetryFailedEvents(arg1:uiapi.RetryFailedEventsRequest):Promise<uiapi.OperationResult>;

export function SaveConfig(arg1:uiapi.SaveConfigRequest):Promise<uiapi.ConfigDTO>;

export function SaveSyncRules(arg1:uiapi.SaveSyncRulesRequest):Promise<uiapi.SyncRulesDTO>;

export function SetAutoStart(arg1:uiapi.SetAutoStartRequest):Promise<uiapi.AutoStartStatus>;

export function SetMCPServerEnabled(arg1:uiapi.SetMCPServerEnabledRequest):Promise<uiapi.MCPServerStatus>;

export function StartAgent():Promise<uiapi.OperationResult>;

export function StopAgent():Promise<uiapi.OperationResult>;

export function TestMySQL(arg1:appconfig.MySQLConfig):Promise<uiapi.TestResult>;

export function TestRabbitMQ(arg1:appconfig.RabbitMQConfig):Promise<uiapi.TestResult>;

export function UnlockAdmin(arg1:uiapi.UnlockAdminRequest):Promise<uiapi.OperationResult>;

export function VerifyExitPassword(arg1:uiapi.VerifyExitPasswordRequest):Promise<uiapi.OperationResult>;
