// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyManagedInstall(arg1) {
  return window['go']['datasyncui']['App']['ApplyManagedInstall'](arg1);
}

export function ExportDiagnosticPackage() {
  return window['go']['datasyncui']['App']['ExportDiagnosticPackage']();
}

export function GetAgentProcessStatus() {
  return window['go']['datasyncui']['App']['GetAgentProcessStatus']();
}

export function GetAuthState() {
  return window['go']['datasyncui']['App']['GetAuthState']();
}

export function GetAutoStart() {
  return window['go']['datasyncui']['App']['GetAutoStart']();
}

export function GetConfig() {
  return window['go']['datasyncui']['App']['GetConfig']();
}

export function GetDeadLetters(arg1) {
  return window['go']['datasyncui']['App']['GetDeadLetters'](arg1);
}

export function GetFailedEvents(arg1) {
  return window['go']['datasyncui']['App']['GetFailedEvents'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['datasyncui']['App']['GetLogs'](arg1);
}

export function GetMCPServerStatus() {
  return window['go']['datasyncui']['App']['GetMCPServerStatus']();
}

export function GetManagedInstallPlan(arg1) {
  return window['go']['datasyncui']['App']['GetManagedInstallPlan'](arg1);
}

export function GetOverview() {
  return window['go']['datasyncui']['App']['GetOverview']();
}

export function GetQueueStatus() {
  return window['go']['datasyncui']['App']['GetQueueStatus']();
}

export function GetSyncRules() {
  return window['go']['datasyncui']['App']['GetSyncRules']();
}

export function LoadConfig(arg1) {
  return window['go']['datasyncui']['App']['LoadConfig'](arg1);
}

export function LockAdmin() {
  return window['go']['datasyncui']['App']['LockAdmin']();
}

export function RequestExit(arg1) {
  return window['go']['datasyncui']['App']['RequestExit'](arg1);
}

export function RestartAgent() {
  return window['go']['datasyncui']['App']['RestartAgent']();
}

export function RetryFailedEvent(arg1) {
  return window['go']['datasyncui']['App']['RetryFailedEvent'](arg1);
}

export function RetryFailedEvents(arg1) {
  return window['go']['datasyncui']['App']['RetryFailedEvents'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['datasyncui']['App']['SaveConfig'](arg1);
}

export function SaveSyncRules(arg1) {
  return window['go']['datasyncui']['App']['SaveSyncRules'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['datasyncui']['App']['SetAutoStart'](arg1);
}

export function SetMCPServerEnabled(arg1) {
  return window['go']['datasyncui']['App']['SetMCPServerEnabled'](arg1);
}

export function StartAgent() {
  return window['go']['datasyncui']['App']['StartAgent']();
}

export function StopAgent() {
  return window['go']['datasyncui']['App']['StopAgent']();
}

export function TestMySQL(arg1) {
  return window['go']['datasyncui']['App']['TestMySQL'](arg1);
}

export function TestRabbitMQ(arg1) {
  return window['go']['datasyncui']['App']['TestRabbitMQ'](arg1);
}

export function UnlockAdmin(arg1) {
  return window['go']['datasyncui']['App']['UnlockAdmin'](arg1);
}

export function VerifyExitPassword(arg1) {
  return window['go']['datasyncui']['App']['VerifyExitPassword'](arg1);
}
