canal.instance.mysql.slaveId=401
canal.instance.gtidon=false
canal.instance.master.address=mysql-edge-longtest:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=
canal.instance.tsdb.enable=false
canal.instance.dbUsername=sync_user
canal.instance.dbPassword=sync_password
canal.instance.connectionCharset=UTF-8
canal.instance.enableDruid=false
canal.instance.filter.regex=scada_edge_longtest\.(collect_data_.*|tag_state_.*)
canal.instance.filter.black.regex=mysql\.slave_.*
canal.mq.topic=edge-longtest-001
canal.mq.partition=0
